[tool.poetry]
name = "dtemulate"
version = "0.1.0"
description = "An emulator platform for Digital Twins"
license = "MIT"
authors = ["martin stoffel <martin.adam.stoffel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mogp-emulator = "^0.7.2"
matplotlib = "^3.7.2"
pytest = "^7.4.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
