name: precommit
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
            - develop
    release:
        types:
            - published

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    pre-commit:
        name: Pre-commit
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - uses: actions/setup-python@v4
            with:
              python-version: "3.12"
          - name: Install poetry
            run: |
              curl -sSL https://install.python-poetry.org | python -

          - name: Configure poetry
            run: |
              poetry config virtualenvs.in-project true

          - name: Install dependencies
            run: |
              poetry install --with dev

          - uses: pre-commit/action@v3.0.0
            with:
              extra_args: --hook-stage manual --all-files
